### ISSUE TITLE
部署在githubpage空白页

### ISSUE THREAD

**Issue by ForCherry** [ztjhz/BetterChatGPT#103]
我按照教程一步一步弄 发布在自己的githubpage io但是是空白页 是因为没有配置域名吗？ 本地开发跑的没有问题

**Comment by ztjhz** [comment]
你有按照这一步吗？

---

如果你不使用自定义域名，需要配置你的 vite.config.ts 文件，在 export default defineConfig({...}) 块内添加 base: '/<REPO>/'，其中 <REPO> 是你的 GitHub 仓库名称，可以从 https://<USERNAME>.github.io/<REPO> 获得（如果你没有改过，<REPO> 应该是 FreeChatGPT）。代码应该是这样的

```typescript
export default defineConfig({
  base: '/REPO/',
  /* 其余的配置在这里 */
});
```

**Comment by zjhewy** [comment]
提示“ fatal: unable to access 'https://github.com/zjhewy/FreeChatGPT.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128”这个是什么原因？需要如何解决？谢谢

**Comment by ztjhz** [comment]
看看[这个](https://github.com/ztjhz/FreeChatGPT/issues/74#issuecomment-1467447162)

**Comment by AXYZdong** [comment]
> 提示“ fatal: unable to access 'https://github.com/zjhewy/FreeChatGPT.git/': The requested URL returned error: 403 Error: Action failed with "The process '/usr/bin/git' failed with exit code 128”这个是什么原因？需要如何解决？谢谢

我也遇到过，可以看看[这个](https://blog.csdn.net/qq_56914146/article/details/128994392)

**Comment by ztjhz** [comment]
有新的部署说明，您可以遵循它。
