### ISSUE TITLE
API key required 

### ISSUE THREAD

**Issue by aopaw** [ztjhz/BetterChatGPT#108]
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

Message from freechatgpt.chat:
Too many request! We recommend changing your API endpoint or API key
------------------------------------------
So that we still need to register an account?  Is there any way to get it work without paying a bill ：）

**Comment by AXYZdong** [comment]
> { "error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null } }
> 
> ## Message from freechatgpt.chat:
> Too many request! We recommend changing your API endpoint or API key
> So that we still need to register an account? Is there any way to get it work without paying a bill ：）

Suggest using your own API.

**Comment by ztjhz** [comment]
Due to limited funding, it is difficult to sustain the free ChatGPT API. We suggest that you use your own API key.

**Comment by cxwx** [comment]
免费的瞬间被用爆了

**Comment by MaeOu** [comment]
我之前一直用的自己的API，最近一直是这个提示；我是得给我自己充值了吗
