### ISSUE TITLE
Seems the services are not available

### ISSUE THREAD

**Issue by 623059008** [ztjhz/BetterChatGPT#115]
Seems like the freechatgpt is not available, do you consider adding more limited rules to increase availability? 
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

Message from freechatgpt.chat:
Too many request! We recommend changing your API endpoint or API key

**Comment by Gerotama** [comment]
![image](https://user-images.githubusercontent.com/103616328/229294522-8de6cdfb-13f6-4a5f-81d6-8d3dd35905c0.png)
yeah i got it but ididnt surpass my quota limit
