### ISSUE TITLE
关于GPT4的多模态功能，后续考虑支持吗？

### ISSUE THREAD

**Issue by Fortytwoo** [ztjhz/BetterChatGPT#123]
因为发现不能发送图片和接受图片

**Comment by ayaka14732** [comment]
OpenAI has not yet released its multimodal API, so we haven't been able to use it or debug it. We'll provide support once it becomes available.

OpenAI 还没有开放多模态的 API，我们都没有用上，也不能调试，等到开放了再作支持。

**Comment by Fortytwoo** [comment]
好的，非常感谢你的回复。
另外我想问一下，如何更改默认的sk配置，我自己部署了一份，给我的同事和朋友使用，但是我不想把我的sk泄露出去。

**Comment by ayaka14732** [comment]
可以私下分享 API Key，让使用的人在网站上填入
