### ISSUE TITLE
i18n的资源文件没有加上base路径，vite打包

### ISSUE THREAD

**Issue by HSQCoollaughing** [ztjhz/BetterChatGPT#128]
![image](https://user-images.githubusercontent.com/29752874/227496910-b009b6b7-dcdc-4ed8-a2ea-a9d1835c67f7.png)

**Comment by HSQCoollaughing** [comment]
少了仓库名

**Comment by ztjhz** [comment]
这个问题最近已被修复。请把这些修改拉到你的仓库里。
