### ISSUE TITLE
feature: add tokenizer

### ISSUE THREAD

**Issue by llegomark** [ztjhz/BetterChatGPT#13]
Add [@dqbd/tiktoken](https://github.com/dqbd/tiktoken) to count prompt tokens

Benchmark: https://github.com/transitive-bullshit/compare-tokenizers

**Comment by saliksik** [comment]
This is cool. If we can count the tokens being generated by the user, we can use it to allow a certain amount of tokens to be consumed by the users in a given time frame. And then, we can integrate authentication using Supabase or any other authentication providers.

**Comment by ayaka14732** [comment]
[@dqbd/tiktoken](https://github.com/dqbd/tiktoken) is not a pure js library and therefore not suitable for frontend

**Comment by saliksik** [comment]
@ayaka14732 I just notice this right now, OpenAI API responded with: { "error": { "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-************************ on requests per min. Limit: 20 / min. Current: 40 / min. Contact support@openai.com if you continue to have issues.", "type": "requests", "param": null, "code": null } }.

Reference: https://platform.openai.com/docs/guides/rate-limits/overview

**Comment by saliksik** [comment]
> [@dqbd/tiktoken](https://github.com/dqbd/tiktoken) is not a pure js library and therefore not suitable for frontend

How about the [gpt3-tokenizer](https://github.com/botisan-ai/gpt3-tokenizer)?
