### ISSUE TITLE
found an API port with unlimited calls

### ISSUE THREAD

**Issue by ChirsJonh8927** [ztjhz/BetterChatGPT#141]
Hi~We may be able to connect this API port as a free endpoint to use。Can we？
Endpoint : https://v1.apigpt.cn/log/
Doc : https://api.aa1.cn/doc/chatgpts.html
Hope this project can develop better

**Comment by DudeNin64** [comment]
I tried it and it just gives me a network error

**Comment by ChirsJonh8927** [comment]
> I tried it and it just gives me a network error
-----------------------------------------------------------------------------

sorry,i posted a wrong endpoint.that's the correct site and the math

addr：https://v1.apigpt.cn/
Return Format：JSON
Request method：GET
Request parameters：https://v1.apigpt.cn/?q=你好&apitype=sql

i tried it before but still can not,but their domo site still can use,i cannot figure it out.

--------------------------------------------------------------
that is the domo json.

// 暂无层级展示，仅供参考 
{
    "code": "Status code",
    "msg": "Get Status",
    "Questions": "Question",
    "ChatGPT_Answer": "Answer from ChatGPT"
}

----------------------------------------------------------------

Is there anyone who can answer my question？@ztjhz @ayaka

**Comment by 050310Y** [comment]
This interface has been tested and is currently usable. I am the maintainer of this interface. If you still have any questions, please provide feedback to my email address in a timely manner. Email address: admin@aa1.cn

finally, thank you for providing the public welfare project

**Comment by Lyapsus** [comment]
It doesn't work for me. How to use it properly?
