### ISSUE TITLE
Failed to execute 'setItem' on 'Storage': Setting the value of 'free-chat-gpt' exceeded the quota. error 

### ISSUE THREAD

**Issue by pbk123461** [ztjhz/BetterChatGPT#148]
There is this error can you fix it plz

**Comment by ztjhz** [comment]
It appears that the storage capacity of your browser has been exceeded locally. To continue using our service, please consider exporting your conversations and clearing them from the local storage. 

To prevent this issue from occurring in the future, we are exploring several solutions. One option is to automatically delete the oldest chat when the local storage is full. Another possibility is to explore alternative storage methods.

**Comment by pbk123461** [comment]
ok thanks

**Comment by ztjhz** [comment]
Hi, wanted to update you that our desktop app have unlimited local storage. You can download it here: https://github.com/ztjhz/BetterChatGPT/releases
