### ISSUE TITLE
This model's maximum context length is 4097 token

### ISSUE THREAD

**Issue by magedhelmy1** [ztjhz/BetterChatGPT#149]
This is the error message

```
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, your messages resulted in 4290 tokens. Please reduce the length of the messages.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}

Rate limited! Please try again later.
```

I have selected `GPT-4-32k` with `Max Token: 32768`.
On the same chat, It works fine in the first 2 questions, but on the third question is throws the error above.
Please let me know how to bypass this, specifically how to make it continue to use the max token during the same chat without going back to the 4092 token.
Big fan of this!

**Comment by ztjhz** [comment]
May I know whether the 3 questions are in the same chat or different chats?

**Comment by magedhelmy1** [comment]
Hi, they are in the same chat

**Comment by ztjhz** [comment]
Have you clicked on confirm after configuring the model parameters?

**Comment by magedhelmy1** [comment]
Upon further investigation, I went to https://platform.openai.com/ and then checked "Usage" and although I had GPT 4 on the frontend of your app and I clicked save, it sent GPT3.5-turbo to the API calls.
I pulled your latest release and that fixed the issue!
Thank you.
