### ISSUE TITLE
WebAssembly.instantiateStreaming() 编译错误

### ISSUE THREAD

**Issue by Bing-lemon** [ztjhz/BetterChatGPT#154]
本地用纯html运行之后，index-9ea73a37.js 这个文件报错： CompileError: WebAssembly.instantiateStreaming(): expected magic word 00 61 73 6d, found 28 6d 6f 64 @+0 ，导致整个js文件不能用，页面点击没有效果，是因为什么呢，是要把这个tiktoken_bg-cfed79ec.wasm 文件放服务器上吗，这个 wasm 必须要用吗，如果不用这个页面整个就没有效果吗

**Comment by Bing-lemon** [comment]
hme = "" + new URL("tiktoken_bg-cfed79ec.wasm",import.meta.url).href      这个得是https 前缀的吗 ，放在服务器上访问的吗

**Comment by ayaka14732** [comment]
>这个 wasm 必须要用吗，如果不用这个页面整个就没有效果吗

wasm 文件肯定是要的

> hme = "" + new URL("tiktoken_bg-cfed79ec.wasm",import.meta.url).href 这个得是https 前缀的吗 ，放在服务器上访问的吗

这个是编译出来的文件，一般不会看的

**Comment by Bing-lemon** [comment]
那 index-9ea73a37.js 这个文件报错： CompileError: WebAssembly.instantiateStreaming(): expected magic word 00 61 73 6d, found 28 6d 6f 64 @+0 ，导致整个js文件不能用，页面点击没有效果  要怎么解决呢

**Comment by Bing-lemon** [comment]
`      pme = async(e={},t)=>{
        let n;
        if (t.startsWith("data:")) {
            const r = t.replace(/^data:.*?base64,/, "");
            let A;
            if (typeof Buffer == "function" && typeof Buffer.from == "function")
                A = Buffer.from(r, "base64");
            else if (typeof atob == "function") {
                const o = atob(r);
                A = new Uint8Array(o.length);
                for (let a = 0; a < o.length; a++)
                    A[a] = o.charCodeAt(a)
            } else
                throw new Error("Cannot decode base64-encoded data URL");
            n = await WebAssembly.instantiate(A, e)
        } else {
            const r = await fetch(t)
              , A = r.headers.get("Content-Type") || "";
            if ("instantiateStreaming"in WebAssembly && A.startsWith("application/wasm"))
                n = await WebAssembly.instantiateStreaming(r, e);
            else {
                const o = await r.arrayBuffer();
                n = await WebAssembly.instantiate(o, e)
            }
        }
        return n.instance.exports
    }`

就是这段里 else     n = await WebAssembly.instantiateStreaming(r, e);   r 和 e 都有，但是 WebAssembly.instantiateStreaming（） 就报错，走不通   为啥呢

**Comment by Bing-lemon** [comment]
` try {
                    n = await WebAssembly.instantiateStreaming(r, e);
                  } catch (e) {
                    console.log(e instanceof TypeError,'TypeError')  // true
                    console.log(e.message)               // "null has no properties"
                    console.log(e.name)                  // "TypeError"
                    console.log(e.fileName)              // "Scratchpad/1"
                    console.log(e.lineNumber)            // 2
                    console.log(e.columnNumber)          // 2
                    console.log(e.stack)                 // "@Scratchpad/2:2:3\n"
                  }`

try  catch了一下，TypeError 返回的 false , 传的 r 和 e 跟源码是一样的

**Comment by Bing-lemon** [comment]
![image](https://user-images.githubusercontent.com/59996029/228406574-16b7178a-5e4b-4585-bddd-8964d4eeb5c9.png)
源码的 .wasm文件是 https 的，本地的事http， 是跟这个有关系吗

**Comment by ayaka14732** [comment]
你是怎么编译的，实在不行就用 Docker 吧

**Comment by Bing-lemon** [comment]
就是把源码拷过来了   应该咋编译啊

**Comment by ayaka14732** [comment]
```
docker build -t better-chatgpt .
docker run -p 3000:3000 better-chatgpt
```

**Comment by Bing-lemon** [comment]
是 纯html 和 js

**Comment by ayaka14732** [comment]
我理解你是在本地直接打开 index.html 文件进行测试，但是遇到了 WebAssembly 的错误。这个错误一般是由于文件加载问题引起的，需要确保加载的是正确的 WebAssembly 文件，你可以尝试将其放到服务器上重新测试。此外，对于编译问题，你可以使用 Docker 进行编译，这样可以避免本地环境因为缺少相关依赖而导致编译失败。

**Comment by Bing-lemon** [comment]
没装docker..... 必须要用docker吗
