### ISSUE TITLE
Ayaka's API is down...

### ISSUE THREAD

**Issue by LyubomirT** [ztjhz/BetterChatGPT#155]
Unfortunately, Ayaka's API for ChatGPT is down, why is it still available to use on the website?

**Comment by ztjhz** [comment]
The free api is down, but the proxy is still working. To use the proxy, you need to supply your own api key.

**Comment by LyubomirT** [comment]
> The free api is down, but the proxy is still working. To use the proxy, you need to supply your own api key.

Oh, in that case, it still can be there. Sorry for disturbing.
