### ISSUE TITLE
Supports using environment variables.

### ISSUE THREAD

**Issue by fernvenue** [ztjhz/BetterChatGPT#159]
Hi, such a great project! Will be so great if we can use environment variables to configure parameters like API endpoint, key and so on :)

**Comment by ztjhz** [comment]
Sure!

**Comment by ayaka14732** [comment]
Hi @fernvenue! I am going to implement this feature. I was wondering if you could provide some clarification regarding how users will be able to set environment variables and how these variables will be loaded in the browser.

Additionally, I am also interested in adding experimental rtl language support to the website. In this regard, I was wondering if you would like to contribute by adding Uyghurche translation to the website. I believe this would be a valuable addition and would enhance the user experience.

**Comment by fernvenue** [comment]
Hi @ayaka14732, thanks for your reply, I think environment variables should help us pre-define some parameters that will replace the default values, so that we can avoid the hassle of configuring them after the service is running, and it's also convenient for us to configure between different devices. The specific implementation may vary, which may depend on the design of the development team :)

By the way, I'll be glad to contribute to translation work.

**Comment by llegomark** [comment]
Up!
