### ISSUE TITLE
给出的代码结果无法复制，并且类型不对

### ISSUE THREAD

**Issue by DuckDuck88** [ztjhz/BetterChatGPT#173]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/45893278/229081070-485b05da-6bc6-4658-a2f4-ba0cdd05554e.png">

**Comment by ayaka14732** [comment]
应该是可以复制的，我自己测试可以复制。这可能是因为协议是 http，浏览器因为安全原因阻止复制，如果是 https 则可以复制

语言错误是因为使用 [rehype-highlight](https://www.npmjs.com/package/rehype-highlight) 自动检测语言，它检测到了错误的语言。OpenAI 官方网页也会出现这种错误

格式错误是因为 ChatGPT 输出的格式不对，不是网页的问题

**Comment by ayaka14732** [comment]
我觉得其实可以不要写出语言，不写就看不出它检测错了 x
