### ISSUE TITLE
Option: Send with Enter key

### ISSUE THREAD

**Issue by firedfly2** [ztjhz/BetterChatGPT#184]
In the Japanese IME, I press the enter key to confirm the conversion, but in this application, it is sent at that moment.
Can you add an option so that it is only sent by Command+Enter?

**Comment by firedfly2** [comment]
Sorry." I found the "Enter to Submit" option (this is the only part that was not translated and I missed it).

**Comment by ayaka14732** [comment]
Thank you for the report. The missing translation has just been added.
