### ISSUE TITLE
remarkMath, remarkGFM, rehypeKatex, seems to not visually apply

### ISSUE THREAD

**Issue by tnga** [ztjhz/BetterChatGPT#193]
![image](https://user-images.githubusercontent.com/12436411/229558668-7c6ff0b2-6763-4469-ba15-93234ac37cca.png)

<s> Also consider to support `rehypeMathJax`, knowing GPT generally use to generated by default MathJax as default for math formula. MathJax have the advantage to be easily selectable as text: eg: ∫ [ √x * cos(x) * e^x ] dx = √x * [ e^x * sin(x) + e^x * cos(x) ] - ∫ [ e^x * sin(x) + e^x * cos(x) ] * 1 / (2√x) dx </s>

**With experience, Katex has a better rendering performence !**

**Comment by ztjhz** [comment]
This has been fixed
