### ISSUE TITLE
feature: plain text output switch

### ISSUE THREAD

**Issue by Honoka55** [ztjhz/BetterChatGPT#20]
Sometimes I want it help me write some markdown without rendering.

Add a switch button so that the answer may be shown in plaintext directly.

**Comment by ayaka14732** [comment]
I think can add a "copy as plain text" button, because display in plain text is essentially the same as editing the response.

**Comment by flycran** [comment]
你可以点击编辑<img style="display: inline" width="28" alt="image" src="https://user-images.githubusercontent.com/86134803/227068170-63c8c6df-ca89-4896-a165-a8f8e1c67aee.png">复制纯文本
