### ISSUE TITLE
Add GitHub sponsor button to the web app

### ISSUE THREAD

**Issue by ayaka14732** [ztjhz/BetterChatGPT#202]
I would like to bring to your attention that the sponsor page of your open-source project is missing a GitHub sponsor button. While Ko-fi, Alipay, and WeChat Pay buttons are present, the lack of a GitHub sponsor button could hinder potential contributors who prefer to support your work on that platform.

Having a GitHub sponsor button would provide a more comprehensive and accessible sponsorship system, allowing more people to contribute to the project. This could also increase the visibility of your work and attract new contributors to the project.

Would you please consider adding a GitHub sponsor button to the sponsor page of your web app?

Thank you for your hard work and dedication to the project.

**Comment by magedhelmy1** [comment]
Hi @ayaka14732  I used the Github sponsor since AliPay and WeChat is blocked here

https://github.com/sponsors/ztjhz

**Comment by ztjhz** [comment]
Done
