### ISSUE TITLE
Remove redundant padding

### ISSUE THREAD

**Issue by ayaka14732** [ztjhz/BetterChatGPT#203]
Current:

![](https://user-images.githubusercontent.com/68557794/229788665-a75ce7a3-9980-42bd-8a80-5f2114affcfe.png)

The red part is a redundant padding and should be removed:

![](https://user-images.githubusercontent.com/68557794/229788701-c4f8add3-4f1e-420f-9e77-626687156675.png)

**Comment by SamuelMiller** [comment]
It makes sense to do so on a desktop, but I wonder if the current padding is good for the mobile phone use to make room for our big fingers? Needs to be tested in both cases.

**Comment by ayaka14732** [comment]
@SamuelMiller You're absolutely right. I didn't take the mobile version into account. An alternative approach is to move the button slightly down so that it's more vertically centered.
