### ISSUE TITLE
Make the conversation history list compact

### ISSUE THREAD

**Issue by ayaka14732** [ztjhz/BetterChatGPT#204]
Currently the conversation takes a lot of space:

![](https://user-images.githubusercontent.com/68557794/229789367-9305fca9-32a6-445c-ba25-0ac875009e65.png)

It should be made compact.

**Comment by SamuelMiller** [comment]
Yes on the desktop the padding could be made a little more compact, and on a phone, it seems pretty good. Have you compared how the spacing works on the phone versus the computer?

**Comment by ztjhz** [comment]
This has been implemented: https://github.com/ztjhz/BetterChatGPT/commit/6c12e67393947d29f58f3e691f03617710d92af0
