### ISSUE TITLE
Error: Exceeded current quota

### ISSUE THREAD

**Issue by Gerotama** [ztjhz/BetterChatGPT#206]
Dont know if im currently limited or if i exceeded in my quota.. as per chat gpt im not exceeded thanks..

![image](https://user-images.githubusercontent.com/103616328/229802476-d523504b-4ec7-4d12-9aeb-18fb65c4feed.png)

**Comment by ztjhz** [comment]
Can you check if your free trial quota has expired?

**Comment by Gerotama** [comment]
found on openai
![image](https://user-images.githubusercontent.com/103616328/229837752-b90befa3-883d-4d4b-876b-e3b87f746af7.png)
