### ISSUE TITLE
npm run dev  error

### ISSUE THREAD

**Issue by wangdongdong9264** [ztjhz/BetterChatGPT#215]
✘ [ERROR] Could not resolve "debug"

    node_modules/micromark/dev/lib/create-tokenizer.js:28:24:
      28 │ import createDebug from 'debug'
         ╵                         ~~~~~~~

  You can mark the path "debug" as external to exclude it from the bundle, which will remove this
  error.
  
  
---

 "version": "1.0.2",

need run `npm i -d debug`

**Comment by wangdongdong9264** [comment]
node -v `v18.14.0`

**Comment by ayaka14732** [comment]
Have you executed `yarn install`?

**Comment by wangdongdong9264** [comment]
> Have you executed `yarn install`?

use `yarn install ` no error
