### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Jimmy6l** [ztjhz/BetterChatGPT#236]
When I send message, I got this 'Failed to fetch' error, what should I do?

**Comment by ztjhz** [comment]
Are you accessing the website from a region that is blocked by OpenAI (e.g. China)?

**Comment by Jimmy6l** [comment]
> 

Yes, but I can use it last day, by the way , I also used the vpn and set in USA.

**Comment by Jimmy6l** [comment]
![image](https://user-images.githubusercontent.com/31723994/232291399-087be876-fa4a-40d7-abef-bbe7fbb4f90f.png)

**Comment by ztjhz** [comment]
you can try changing the api endpoint to https://chatgpt-api.shn.hk/v1/ in the api settings.

**Comment by Jimmy6l** [comment]
> you can try changing the api endpoint to https://chatgpt-api.shn.hk/v1/ in the api settings.

Ok, thanks your answers.  I changed it But got another error. The api endpoint I used before is https://free.churchless.tech/v1/chat/completions.
![image](https://user-images.githubusercontent.com/31723994/232296721-d27d1b00-d004-4618-b3d7-b054ebd46ce1.png)
![image](https://user-images.githubusercontent.com/31723994/232296775-bf549a2f-629c-412f-bea8-70529407eff2.png)

**Comment by ztjhz** [comment]
I see, that free endpoint is currently down right now due to patches by OpenAI. It is recommended that you use the official endpoint to avoid disruptions.

**Comment by Jimmy6l** [comment]
Hmm, I think so too, thanks for your reply.
