### ISSUE TITLE
请问有没有选项关闭markdown渲染？

### ISSUE THREAD

**Issue by wanzhiyu** [ztjhz/BetterChatGPT#242]
我在调试正则表达式的时候发现这个markdown渲染很影响我的判断，请问能不能给用户一个开关markdown渲染选项

**Comment by ztjhz** [comment]
刚加了，可以按这个：

![image](https://user-images.githubusercontent.com/59118459/233607373-9614355c-30f3-4a41-a1f1-24955dbe72c4.png)
