### ISSUE TITLE
[Feature Request/Modification] show conversation cost per individual threads, in addition to just the site's usage as a whole

### ISSUE THREAD

**Issue by jackschedel** [ztjhz/BetterChatGPT#254]

**Comment by ztjhz** [comment]
This can be implemented. 👍

Can you provide more context on why it would be useful to view the cost per thread? Understanding the specific use case would help us better address your needs.

**Comment by jackschedel** [comment]
Atleast for me, I care less about the total cost I've spent and care more about how much it cost for me to fix a single thing, which can then better translate into "this would've taken me an hour to do by myself, but 4 messages and $0.19 later, I have it completed".
It would also be cool to have total folder costs too.

**Comment by ztjhz** [comment]
I see, this is good 👍
