### ISSUE TITLE
[Feature Request, Niche + Low Priority] add support for Google API Client Secret for desktop app version to allow for saved logins

### ISSUE THREAD

**Issue by jackschedel** [ztjhz/BetterChatGPT#256]
obviously you still don't want to have your client secret public so it wouldnt be populated by default, but would be nice for custom personal builds

**Comment by ztjhz** [comment]
The problem is that nothing can be kept secret in the client application. If we store the secret in the desktop app, the end user would be able to reverse engineer it.

**Comment by jackschedel** [comment]
yes, i understand. that's why I said that "it wouldnt be populated by default, but would be nice for custom personal builds". it would only be populated by a client with their own Google Console endpoint

It would make the desktop version alot nicer

**Comment by ztjhz** [comment]
Is it the end user being able to change the client id being used?

**Comment by jackschedel** [comment]
Imo its only valuable if it makes use of the client secret, so there isn't the requirement for constant user logins

**Comment by ztjhz** [comment]
I see, so the user enter their own client secret and client id?
