### ISSUE TITLE
any plan to support railway.app?

### ISSUE THREAD

**Issue by Root-FTW** [ztjhz/BetterChatGPT#260]
any plan to support railway.app?

**Comment by ztjhz** [comment]
Better ChatGPT is a fully frontend application. So it is able to deploy to any hosting services, including railway.app.

**Comment by Root-FTW** [comment]
> Better ChatGPT is a fully frontend application. So it is able to deploy to any hosting services, including railway.app.

hI deployed it in railway.app and it doesn't seem to work:

https://adan-production-61f1.up.railway.app/

**Comment by ztjhz** [comment]
It seems like there is an internal server error. How did you deploy it on railway.app?

**Comment by Root-FTW** [comment]
> It seems like there is an internal server error. How did you deploy it on railway.app?

I just opened my railwayapp, I set it to deploy a github repository, I forked your repository, it deployed and that's the error it shows

**Comment by ztjhz** [comment]
What error do you see in the railway?
