### ISSUE TITLE
API key from .env file not being used

### ISSUE THREAD

**Issue by aarong416** [ztjhz/BetterChatGPT#261]
I'm having a problem where the environment variable `VITE_OPENAI_API_KEY` is being ready correctly from the `.env` file, but its value is just an empty string `''` in the component.

I copied the `.env.example` file to `.env`, deleted all the variables except for `VITE_OPENAI_API_KEY`, so now I just have a `.env` file that looks like the following:

```
VITE_OPENAI_API_KEY=my-api-key
```

When I run the application and try to send a message, I get the error `No API key supplied! Please check your API settings.` even though the API key is correctly set. If I manually set it under the `API` section, it works fine. The reason I want to set it up globally like this is so that it doesn't have to be configured for each person that accesses the server.

So I opened up the project to do some debugging, starting with the store (`auth-slice.ts`):

```javascript
apiKey: (function() { console.log('The API key from the env file:', import.meta.env.VITE_OPENAI_API_KEY || undefined); return import.meta.env.VITE_OPENAI_API_KEY || undefined; } ()),
```

The above line correctly outputs the API key defined in the `.env` file to the console (I just created an anonymous function to be called straight away to get as close to the source of the problem as I could. It still has a `return` statement that returns the API key.)

So then I went into `App.tsx` and added the following code to retrieve the value of the `apiKey` variable in the store:

`const apiKey = useStore(state => state.apiKey);`

and then I have the following `useEffect`:

```javascript
useEffect(() => {
    document.documentElement.lang = i18n.language;
    i18n.on('languageChanged', (lng) => {
      document.documentElement.lang = lng;
    });

    console.log('API key:', apiKey);
  }, []);
```

And the above `console.log` statement outputs `API key: <empty string` in the browser.

I have no idea what the problem is here. Why would the value be read from the `.env` file, but not stored property in the state variable in the store?

I thought that it could possibly be a timing issue, so I added a `setTimeout` with a timeout of `2000` milliseconds in the `useEffect` hook, but that didn't change anything. I also tried outputting the API key in the HTML, but still the same thing.

I have never worked with `zustand` before, so it's possible that there is just something that I don't understand about the library. I have worked with stores before in SPAs, so I don't see why this isn't working.

If it is something to do with `zustand` and it would be better for me to open an issue there, I'll be happy to do that, but I wasn't sure, so I just created one here.

PS: I ran the server with `yarn dev --host --port 80`

**Comment by ztjhz** [comment]
The api key defined in `VITE_OPENAI_API_KEY` would only be applied to first visitors. After they visit the website, the api key is stored in the local storage and every time they refresh the page, the local storage api key will be used instead. 

In your case, it is possible that you set the `VITE_OPENAI_API_KEY` only after you have visited the page once, which might have caused it to not be loaded. You can try opening the website in incognito or clear the cache and try again.

**Comment by aarong416** [comment]
That makes sense. I tried restarting my browser and clearing all data, and it does seem to be working now.

Thank you.
