### ISSUE TITLE
本地化部署Website关于回复的md格式代码按钮无法复制粘贴

### ISSUE THREAD

**Issue by AuroraMaster** [ztjhz/BetterChatGPT#262]
本地部署后
在代码询问时，回复的代码能够正常用Markdown识别匹配，但无法使用上下两端的复制粘贴按钮
![image](https://user-images.githubusercontent.com/45430047/235196770-0c6be82b-c53d-4c64-94bc-a96a3e974193.png)
![image](https://user-images.githubusercontent.com/45430047/235196867-22eb2bf6-8fc4-48cc-8fd9-04703a73d974.png)
这两个地方按钮在本地化部署后都无法使用，点击button但没有任何提示并且也没有复制操作，请问是怎么回事，或是可以做些什么

**Comment by ztjhz** [comment]
有可能是 http 的关系. 你怎么部署？

**Comment by AuroraMaster** [comment]
确实是http的问题，我本地设置了一个nginx反代，在设置反代WebSocket后

网络环境
win10 host中allgpt.com到wsl2 debian的172.30.17.89，再nginx监听域名80反代到debian的127.0.0.1:5173
除了直接127.0.0.1(localhost/user等）:5173能完好使用外，其他关于host域名映射后皆功能残缺(几乎都是浏览器支持但被禁止使用），可能是浏览器安全策略{可能}
我决定暂时不考虑这种方法
