### ISSUE TITLE
[Feature Request] Clear prompt library

### ISSUE THREAD

**Issue by SimonB97** [ztjhz/BetterChatGPT#266]
Hi, nice work, thank you!

It would be cool to have an option to remove all or multiple prompts from the prpmpt library at once. Removing them one by one is pretty slow.

Thanks!

**Comment by ztjhz** [comment]
This can be done.

**Comment by SimonB97** [comment]
Thank you, could you also tell me how, maybe?

**Comment by ztjhz** [comment]
Oh, I meant that we can implement this.

**Comment by SimonB97** [comment]
Ah, cool thing then! Thanks again
