### ISSUE TITLE
Better GPT webpage cannot be opened

### ISSUE THREAD

**Issue by jjjj8866** [ztjhz/BetterChatGPT#276]
Better GPT webpage cannot be opened

**Comment by ztjhz** [comment]
Can it be accessed with a VPN?

**Comment by jjjj8866** [comment]
你好。已收到你的来信，请勿多次发送。谢谢!

**Comment by jjjj8866** [comment]
> 可以用VPN访问吗？

I can access this website using VPN, but I cannot access this website using China's network. Why is that?

**Comment by ztjhz** [comment]
the domain bettergpt.chat is blocked in china
