### ISSUE TITLE
Unable to have Google Sync on local docker instance

### ISSUE THREAD

**Issue by raedkit** [ztjhz/BetterChatGPT#286]
Hi,

I tried to host my own instance locally using local docker instance. Unfortunately, I'm not seeing Google Sync button as on https://bettergpt.chat/
Am I missing something ? Thanks in advance for your help.

**Comment by ztjhz** [comment]
You will need to set `VITE_GOOGLE_CLIENT_ID` in the environment variables.

**Comment by raedkit** [comment]
> You will need to set `VITE_GOOGLE_CLIENT_ID` in the environment variables.
> 
> See how to get the Google Client ID here: https://support.google.com/cloud/answer/6158849?hl=en#zippy=%2Cweb-applications

Thank you I will try this

**Comment by jagauthier** [comment]
Hello,

 I have done this, but I don't see the Google Sync option showing up.
The docker logs do not seem to have any indication about what may be happening.
