### ISSUE TITLE
default model

### ISSUE THREAD

**Issue by DavidHJong** [ztjhz/BetterChatGPT#307]
when creating a new chat, the default model is set to gpt-3.5-turbo. how can I change the default model to gpt-4 for each new chat? I want to add an option in settings for default model but I don't know how. anyone can help?

**Comment by ztjhz** [comment]
Click on the settings in the left sidebar

Then click on default chat config:
![image](https://github.com/ztjhz/BetterChatGPT/assets/59118459/abe357f9-14c1-4e6e-95a0-2910ab618c7a)

Then modify the model and click the `Confirm` button at the bottom.

**Comment by DavidHJong** [comment]
thank you. that works.
