### ISSUE TITLE
Can't put text-davinci-003 as the model

### ISSUE THREAD

**Issue by nacho00112** [ztjhz/BetterChatGPT#309]
APi's like the one from https://github.com/PawanOsman/ChatGPT (`api.pawan.krd`) allows using `text-davinci-003` as conversational model, but the page doesn't has it in the list.

Anyway putting an option that let the user write the model he want could be a good idea.

**Comment by ayaka14732** [comment]
Is is worth pointing out that `text-davinci-003` is not a conversation model. It requires extra work to make it conversational, and the result would not be satisfying.

**Comment by nacho00112** [comment]
> Is is worth pointing out that `text-davinci-003` is not a conversation model. It requires extra work to make it conversational, and the result would not be satisfying.

I thought that both `text-davinci-003` and `gpt-3.5-turbo` are the same of good.
