### ISSUE TITLE
How to Update

### ISSUE THREAD

**Issue by Philomath88** [ztjhz/BetterChatGPT#313]
Hi,

I downloaded the mac desktop version - how can I update to the latest version without losing my conversation history?

**Comment by ayaka14732** [comment]
You can export the data by clicking the "Import / Export" button on the sidebar. When you download a new version, you can import the data in the new version.

**Comment by mariodian** [comment]
You shouldn't lose your conversation history when you update though, because it's saved in `~/Application Support/better-chatgpt` and the app update should not even touch the folder.
