### ISSUE TITLE
[Build Help] Convenient way to know whether launched as electron or in browser

### ISSUE THREAD

**Issue by SilverMarcs** [ztjhz/BetterChatGPT#318]
Title says it all. If i want to add logic to do something only if the app launched in electron mode, whats the simplest way to do this checking?

**Comment by mariodian** [comment]
`window` object is only available in a browser.

````javascript
if(typeof window === 'undefined')
    console.log('running via electron')
else
    console.log('running in a browser')
````

**Comment by SilverMarcs** [comment]
@mariodian will this work with how this app is structured? It seems the app opens a server in a port and loads it there regardless of opening in a browser or through electron?

**Comment by mariodian** [comment]
You're right. Oddly `window` is even available when you build it via `yarn make`.

**Comment by SilverMarcs** [comment]
Ah this seems to be working. I'll perform some testing on other platforms and see how it behaves. Thanks!
