### ISSUE TITLE
betterchatgpt doesnt working suddenly

### ISSUE THREAD

**Issue by AxmanaleX** [ztjhz/BetterChatGPT#320]
i have no code knowledge or programming, so i apologize in advance, i was using betterchatgpt as usual but suddenly when i prompt it, it only responds me with this:

{"error":{"code":"500","details":"#8e8ea0;text-align:center}@media (prefers-color-scheme:dark){body{background-color:#343541}.logo{color:#acacbe}}\u003c/style\u003e\n  \n\u003c/head\u003e\n  \u003cbody\u003e\n    \u003cdiv class=\"container\"\u003e\n      \u003cdiv class=\"logo\"\u003e\n        \u003csvg\n          width=\"41\"\n          height=\"41\"\n          viewBox=\"0 0 41 41\"\n          fill=\"none\"\n          xmlns=\"http://www.w3.org/2000/svg\"\n          strokeWidth=\"2\"\n          class=\"scale-appear\"\n        \u003e\n          \u003cpath\n            d=\"M37.5324 16.8707C37.9808 15.5241 38.1363 14.0974 37.9886 12.6859C37.8409 11.2744 37.3934 9.91076 36.676 8.68622C35.6126 6.83404 33.9882 5.3676 32.0373 4.4985C30.0864 3.62941 27.9098 3.40259 25.8215 3.85078C24.8796 2.7893 23.7219 1.94125 22.4257 1.36341C21.1295 0.785575 19.7249 0.491269 18.3058 0.500197C16.1708 0.495044 14.0893 1.16803 12.3614 2.42214C10.6335 3.67624 9.34853 5.44666 8.6917 7.47815C7.30085 7.76286 5.98686 8.3414 4.8377 9.17505C3.68854 10.0087 2.73073 11.0782 2.02839 12.312C0.956464 14.1591 0.498905 16.2988 0.721698 18.4228C0.944492 20.5467 1.83612 22.5449 3.268 24.1293C2.81966 25.4759 2.66413 26.9026 2.81182 28.3141C2.95951 29.7256 3.40701 31.0892 4.12437 32.3138C5.18791 34.1659 6.8123 35.6322 8.76321 36.5013C10.7141 37.3704 12.8907 37.5973 14.9789 37.1492C15.9208 38.2107 17.0786 39.0587 18.3747 39.6366C19.6709 40.2144 21.0755 40.5087 22.4946 40.4998C24.6307 40.5054 26.7133 39.8321 28.4418 38.5772C30.1704 37.3223 31.4556 35.5506 32.1119 33.5179C33.5027 33.2332 34.8167 32.6547 35.9659 31.821C37.115 30.9874 38.0728 29.9178 38.7752 28.684C39.8458 26.8371 40.3023 24.6979 40.0789 22.5748C39.8556 20.4517 38.9639 18.4544 37.5324 16.8707ZM22.4978 37.8849C20.7443 37.8874 19.0459 37.2733 17.6994 36.1501C17.7601 36.117 17.8666 36.0586 17.936 36.0161L25.9004 31.4156C26.1003 31.3019 26.2663 31.137 26.3813 30.9378C26.4964 30.7386 26.5563 30.5124 26.5549 30.2825V19.0542L29.9213 20.998C29.9389 21.0068 29.9541 21.0198 29.9656 21.0359C29.977 21.052 29.9842 21.0707 29.9867 21.0902V30.3889C29.9842 32.375 29.1946 34.2791 27.7909 35.6841C26.3872 37.0892 24.4838 37.8806 22.4978 37.8849ZM6.39227 31.0064C5.51397 29.4888 5.19742 27.7107 5.49804 25.9832C5.55718 26.0187 5.66048 26.0818 5.73461 26.1244L13.699 30.7248C13.8975 30.8408 14.1233 30.902 14.3532 30.902C14.583 30.902 14.8088 30.8408 15.0073 30.7248L24.731 25.1103V28.9979C24.7321 29.0177 24.7283 29.0376 24.7199 29.0556C24.7115 29.0736 24.6988 29.0893 24.6829 29.1012L16.6317 33.7497C14.9096 34.7416 12.8643 35.0097 10.9447 34.4954C9.02506 33.9811 7.38785 32.7263 6.39227 31.0064ZM4.29707 13.6194C5.17156 12.0998 6.55279 10.9364 8.19885 10.3327C8.19885 10.4013 8.19491 10.5228 8.19491 10.6071V19.808C8.19351 20.0378 8.25334 20.2638 8.36823 20.4629C8.48312 20.6619 8.64893 20.8267 8.84863 20.9404L18.5723 26.5542L15.206 28.4979C15.1894 28.5089 15.1703 28.5155 15.1505 28.5173C15.1307 28.5191 15.1107 28.516 15.0924 28.5082L7.04046 23.8557C5.32135 22.8601 4.06716 21.2235 3.55289 19.3046C3.03862 17.3858 3.30624 15.3413 4.29707 13.6194ZM31.955 20.0556L22.2312 14.4411L25.5976 12.4981C25.6142 12.4872 25.6333 12.4805 25.6531 12.4787C25.6729 12.4769 25.6928 12.4801 25.7111 12.4879L33.7631 17.1364C34.9967 17.849 36.0017 18.8982 36.6606 20.1613C37.3194 21.4244 37.6047 22.849 37.4832 24.2684C37.3617 25.6878 36.8382 27.0432 35.9743 28.1759C35.1103 29.3086 33.9415 30.1717 32.6047 30.6641C32.6047 30.5947 32.6047 30.4733 32.6047 30.3889V21.188C32.6066 20.9586 32.5474 20.7328 32.4332 20.5338C32.319 20.3348 32.154 20.1698 31.955 20.0556ZM35.3055 15.0128C35.2464 14.9765 35.1431 14.9142 35.069 14.8717L27.1045 10.2712C26.906 10.1554 26.6803 10.0943 26.4504 10.0943C26.2206 10.0943 25.9948 10.1554 25.7963 10.2712L16.0726 15.8858V11.9982C16.0715 11.9783 16.0753 11.9585 16.0837 11.9405C16.0921 11.9225 16.1048 11.9068 16.1207 11.8949L24.1719 7.25025C25.4053 6.53903 26.8158 6.19376 28.2383 6.25482C29.6608 6.31589 31.0364 6.78077 32.2044 7.59508C33.3723 8.40939 34.2842 9.53945 34.8334 10.8531C35.3826 12.1667 35.5464 13.6095 35.3055 15.0128ZM14.2424 21.9419L10.8752 19.9981C10.8576 19.9893 10.8423 19.9763 10.8309 19.9602C10.8195 19.9441 10.8122 19.9254 10.8098 19.9058V10.6071C10.8107 9.18295 11.2173 7.78848 11.9819 6.58696C12.7466 5.38544 13.8377 4.42659 15.1275 3.82264C16.4173 3.21869 17.8524 2.99464 19.2649 3.1767C20.6775 3.35876 22.0089 3.93941 23.1034 4.85067C23.0427 4.88379 22.937 4.94215 22.8668 4.98473L14.9024 9.58517C14.7025 9.69878 14.5366 9.86356 14.4215 10.0626C14.3065 10.2616 14.2466 10.4877 14.2479 10.7175L14.2424 21.9419ZM16.071 17.9991L20.4018 15.4978L24.7325 17.9975V22.9985L20.4018 25.4983L16.071 22.9985V17.9991Z\"\n            fill=\"currentColor\"\n          /\u003e\n        \u003c/svg\u003e\n      \u003c/div\u003e\n      \u003cdiv class=\"data\"\u003e\u003cform id=\"challenge-form\" class=\"challenge-form\" action=\"/backend-api/conversation?__cf_chl_f_tk=UNUFZGGTs2H1Z9EMEujiVinY2IKdeQhtTBEx5hGqK6s-1685660844-0-gaNycGzNFGU\" method=\"POST\" enctype=\"application/x-www-form-urlencoded\"\u003e\n    \u003cdiv id=\"cf-please-wait\"\u003e\n        \u003cdiv id=\"spinner\"\u003e\n            \u003cdiv id=\"cf-bubbles\"\u003e\n                \u003cdiv class=\"bubbles\"\u003e\u003c/div\u003e\n                \u003cdiv class=\"bubbles\"\u003e\u003c/div\u003e\n                \u003cdiv class=\"bubbles\"\u003e\u003c/div\u003e\n            \u003c/div\u003e\n        \u003c/div\u003e\n        \u003cp id=\"cf-spinner-please-wait\"\u003ePlease stand by, while we are checking your browser...\u003c/p\u003e\n        \u003cp id=\"cf-spinner-redirecting\" style=\"display:none\"\u003eRedirecting...\u003c/p\u003e\n    \u003c/div\u003e\n    \u003cinput type=\"hidden\" name=\"md\" value=\"18Y64gl44bHBiHJV825qa7zuZ_jjybvFDF2n39vWgiI-1685660844-0-AWFbC0CYfPjb3OLNtvORCXezGoU__-LhnhPS8KnL0qQYMM6bqUhkjPWQslrf6IVTOvKSzppZyUUUHeHUVj8Um49MG6MRM7-gmX5Pdttq2uFUDmsZc8LF6fIcahaPVSQVnV7e8Rbq4WOP3rPTBnaFd2ZiRvhyFgxdYy8vTIXFdtnZ2ddWX0EF1D8TwKfs0nPsGpev0oVawhd7N_hzwo5Sl2AE3awHQ6Ch-IOef6rLjlcbgFLZDL2rtjT7XbIf9Q43TgEz6sxxiRV8O4dbtOPzVcmXz6eKS7DtlL4vKQexcZvDsS78kbod64ENLxFLhRoAv5RBwVTghjj7BSi4_VOsa-ZWDfKagv1zIn8_ybm2Y1x0eiWMjzX0f3PsiFKJZMMtyXChzDj7xCldUdL2imFrMKyaG0h2yp-g095x1IPpdPsIoZMGt2FSCeIbVHLOa89y1VSeG8oTh9NXJnslfPFWQSMQSDoVNHXWaH6d3wwfv5vudn7YHpmGzspGlmRf3Eh-rBjCuAP163BMIoj53jqRzM-wFWxcWRA76pOhpXXhUldiANQqX5VXF3wFg7Lu5pjYs-MotxwWSQHtQWId0RNMr9M0EXvDfGyIEIhK7IE2rX1b-nGAvjc_4oJkz9AzKR2GyEtD3H3nDL3yVqPfNAf8nIIxMD0JB9jz13uyczqA4Bou3xcacetRLwiLtKKHQkoGOWK_phdg9npDBdlIUm7n0aPdCIi15l5CW8VTReKPV_dDT0Ktrmjxc6-sLSaJHObLFmKYx2a43vLdX3QbKNJ8Hrbn7mQGs88c9izjq7fO3snFUL5WEcTfEJCzrXcDypZ1HI07t8_DsEH6Af0uBuB7KG-ShbH_qdHVYCNEWORKpvq7h2UF7U7wom8Q16QHXv7indRIA98BJ7mYTjzP7x0xyL8W5p3jlFHW_S_zI1lqft1M-vC-kcBWFBVfMbDlr0irf7RKEotO9Ya9XhIZqXHyiUMPnPk_uZzdNGxwEa75UzVbff7jBWpb_8r8M-lB-xkfmGy--hzd6YcP5N8iKZ2YdaCIhSY_LNxFURm3FOy17A6IBAmfFy9nRGeODaWjVSCaJGp62yviExYregmbL4DIHtqe38j5w1kpsyLSBufBWTIuhfwbMGgkT9IQLvKeIQnlUErAhz2tQ7IImG6Thq9utRNx73TUPlvz414OOjHlx5WnNpkvVkx_42H2ansQjKHF68t-MgVovJEeUikES5aMjTlv4TXrkUW8i3lPsEEun6zvw6ceWA4kbGDt16e0GTFhkcbw5uJCbFKPcCdFMLFp5oDWIgzHv7BvjOhoiF4dcTeUxGiurXqPERkHl_dVnYa1S3EHvFWbYCfSZIfFDPp0jyaonS7M6xgdQFvq9fkkY8ClFBYKXmRRlP9V5dTquZU1GM-bZdoOXH1SJDTM3AfEh-y4jZyaDGxtvbZFA1C-2Qh41ZoebDhW9f7id4eQI67amt8EXxCx5yiPVlkniGZ4qJ0r7apgiXaVucpoCcFxmXs6622T0x7pwq5auPwblPCzWr_4Hgw5hSlXxheo79kQw5xORqmzLz7MyHo6RtpM2xcSWl3Rf0XdQRkVQAjsDibW-7sHNglDl_sFM4jFamrI5nLaa6-6eUvFYrM_9OtxQetz_HeqYohWzM5ie6AnKcvam0i_hBfbwdslPG6HDauoXbowDp-NFfG2G5Ko0-wE3IK2Bs_TUuHjWw1BvBDL1gJo80UhJ2FGPDtvmmD7eqgHrd-myLNAK9ZwqkWNRrULzB9anB6qpMAJrPyk94KPFH0JUb9LRzRk6sDIG1bOltoxpIniHLPLzqEMjcr7bbHDrulF7MghrWY8OJTvNYQdJ_P1Il_H1-fmK73ArO0sepMSYLE0CqCKI0uZPI-NkUB6Hn3DERMgMzLFG6Ys96tyxwRfsC1DFZsP240KWnZw1dpEzUOwVemxAaR5-kW6zucbFb8cHXVVfuV-yOIKSoS2dHBRMA_edsMyOmfwSWzjeIu2ZgvJkCantvwyLlpg1JAIFqm8PHWqcA22oNtnbUOpvZvNv104v5Rc8FOpenwrCEDLgzpBDDcBc-5nReBSUIEN5n0XKg8YoLpXDzi_IWGs9AaSJqr_Hf4N27G3cp_yGV83j0NmvpLOa89I7tKE_TvxXJaB1JuzLweNInZevJ72ggRXpnHzOFLSaHOHh4Cq1yj2TGsZaxvlIGjVPZmWBbzwvX4cDnXZZFDs9iFx0NmoBLfcCTl1fZCpCCs0yszx6707suNGxRIUPA4oR6Vv6m6dWPg6a4dib65T-97zsSwkcUqGcMyZjL1xlT1RAf0Hr8JgzkobTNmoTRZqc-7vBJtSZC-amvm7_VKWwHVT2oYnqRE-fNjtrTbj_AcqXogLXh4E5ENNT1Q6ATOd0h1ucIfMgCKtJ21HG2N_Ol_IQuHDM9THy9iyaLUGl6BT5mNlap5EgwMlRDwlnH7lwaJBgZAXhZDtMOOmQMbZlUOAXqb5Z6iZN8yYu06qeTPGd67BaWu-C2hQ3-aJsgW5FbfB7gsNCqULrGFL92NFq8e_dsDBr6j33sP4vEkKkxMTj4CSwyjuH0RNtTEMT8GhBB1sbf2IasLiFMbYCfAniwDNzd6KHOiScTub938TK-AVQnYJbLPH3_rnzY0vmPfXX4Ge8NesDReMuKn8kHHCNblXEFzTLH-lDLmlG39-Vq_neG4Zy2Vu-JozmCN-o1qdjYjoy7rzk4oro-uSRn7-4WUhvpf_RSdqh1vweUEd-M7rfZC4AsMJqYKlWzPs7oMuNgS0StEcPfMLmhNrumAPL9dU_v_JbA0FCrDU_IkB116Q5g-nHoLnaSao5x5cc_BV3wLgN7qO8F3hxrPRj-q3y0XVLpZs0wMHDzikzGQbMOzMVe6F4GbaliI2liDvxBDcnoEKJFmnZFFEL5t9zPZIHv2rg1F_cDXhtjcn9R5sydWcYrpChAKGBYCL0mO5aL695p0bjyIG6tLpyFz06NCZBJhwn3fAzqb06RKGbuMqo2d_9cm7Dzaypo_W8AgvYfyx3xyYy2E0wKSKUlT_iG_dNHaGMbkgRo5giO8BmLgWy3SE8gNuhhvS7L9r2j6p6wfvwjelprlli-UOqUOzqIwLvXhvLAmlAjHsPbOkAQ_0az0E624ELQtOlzS-5Hh5pvdk3CuavrdYJXQeqNQyaxdzECNzdwVVH8Hi10uvDcdCjKa8PW7kpuK2xoxMJllw7y2g1moonEHaGIiOi0kqJzh5IYO0NO5pWTX4c_kVzO3yt3Ofxsko68gGkHkYQ9MkhbYRVz4XRmPYwwDgmjdBscDfKv0H1d6sGiusKH0tjRsiGlsR9T9NNOWcZJOT0Olq4keRncF0MLkXN8wdwFSGXsuXWDFs-VS-90H7c_C-cebSp27p02zoXtDYUqCkFdZh42KFaYlZCqXfXycV0C2Si9GkYbjNTmZyR20z2ECj07TfMVxXTp54bzAUYamKVZ8ZbAvZDPdcjsEu4Hui7hJV1rbdSReRQjyFZ7h0CDSDO_Qzo3sF6B9vPvA9f2n4rOX72jtBLMYJdleYq1VO8takF9vS6jE9cWpO4Yuy9esDto7oz5s_F1PVqSFqPf5gCUwk-qBcqZVevavztxYJHNgdv7KQmmH6DNF1EOXXGfNDPRlkvHYJMOgMcZ22bwrE5iP_sSH0WOP1X3yT89jFX1vU7hS6Q0BrNIJQUtQHJOaCXVZclirMWCBuhvjZAKDYUa7tKlo4FsVhRy-ms4mKjOcNOD7aVdKpgJLlaB1-bjSMtS0nT6p7d32wJ__H8ayO0n0IHTMWX17EaWnZ7fyaP0ZXLuCkFte3gtWjS1YiEAqZw0CD38JALCBbXtCOqLbMv5O1dkXBa01MjBSSyKXTWjwLai9Z1OYs-0GlSMp2FBs7nILCJW7LF6p2278ZFxy6FKxLelqP-D69EYb6Aka7vkbZ9f2NzykyFSfomkpw51GoXF9CBZRVEOBD1yOnDGqHOZpWiLbt9WNgWIeL_1k9jkTQDPpL28lJz8pyT4kd1e6ZcaHM6UX49DxwCJvK0zz3B6DcgCwnRKP3MK2k9DU3Ls-45qnHUKbgpAlk2N-OQHDSoGQHvTCLVSC6iELrwI_ybZqVADEry7nKKFnLwNvvty-rChyyrTiaDBV2xbUEJaN2_8_Wgvm_aiekgT1RUJ7EvNwjs9Hvt57mnCTacKYP91NDbSquTGrs6MoJWv6Iw3Xztjge88-5rfrj045KE-j4h06NUMI9JscvQhZdtwbu3wUxRRbEmJ2vrH0oFcOv9CzHLk0z3CskTqyFNfaBc5VTOrxPGwqZ7rkR365YC7D5ztnCNuMgEWNOZMiSbFTxHUBa7CLFZgwCgCB9KbaqI8CrbaFihtjNA7ffZFZPvTVRHjdmwVIr4Q_40OHgjbdadaRAwDeg2mdl_eiTW4ZlFVlBP3xou09YY6mi-0SMktkRIfyv6TZTzAPlmw-R_62apda8oU9OpsZcD9Oa-Dfwq3UBAKOrRFYPbqnoolvpC7aM7VCJSw8kaPqC9wsFxmWt4k-fSG6gtpa1blSwm_EReh22101iLjjR-WWT5oPdlDpoP4uBQQ3n7-nuQYSgFcTSHuO_UfQ6MBUCeOIvNVSYYRDUErRwXVnJ7cvyOXmqIndGbOoRI5ODISSrweeHegKYqmF4x-xZ3pBU2uDcjJkOeRISolZxhmS2skd17r2Ppm6m2oiL_nc68fsjAwMJp3BMiJWegMVVQtfJ3V84U_it8nhMiAQw-ORm51D4UUn1P-oQGBTKpBMsb2_WaSR4uOL1AKDwSFD_Don5WUxZdl2wP5pbewaCElL_P9UOP3vnlV2e96pQJnsYhT5yZ43MJ7nZzjNAY49c0WcNqozwVhKaYPA_iV1_mWEeXOWKN4dBr2cE3Fo9l3pB8M78Q5B6lXNSIIP7aS8ro9M773vhhtMObgUxxR1x3Fx2BzgXxp_qeTHmoXKdZMgq31EG-G_h_I86GrT4cGkuvJ-GAyJjUbVcK6ibcvekCpo3p5m52fjTavOCn_DkAIgFjRZF0aytnEPvxUZYH5GIWZp_fw4_2hpZS77oHBHAIqMIspxijn_SWN63nivrwSS5MPRFBqW6eGOAJ6YzVljpZR3NttcMrFaOiHHI4qNGjiMWTcsYWwe7VnH6\" /\u003e\n    \u003cnoscript id=\"cf-captcha-bookmark\" class=\"cf-captcha-info\"\u003e\n        \u003ch1 style=\"color:#bd2426;\"\u003ePlease turn JavaScript on and reload the page.\u003c/h1\u003e\n    \u003c/noscript\u003e\n    \u003cdiv id=\"no-cookie-warning\" class=\"cookie-warning\" style=\"display:none\"\u003e\n        \u003cp style=\"color:#bd2426;\"\u003ePlease enable Cookies and reload the page.\u003c/p\u003e\n    \u003c/div\u003e\n    \u003cdiv id=\"trk_jschal_js\" style=\"display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7d0b1cd3584a3584')\"\u003e\u003c/div\u003e\n\u003c/form\u003e\n\u003cscript\u003e\n    (function(){\n        window._cf_chl_opt={\n            cvId: '2',\n            cZone: 'chat.openai.com',\n            cType: 'managed',\n            cNounce: '87809',\n            cRay: '7d0b1cd3584a3584',\n            cHash: 'd90ff77fe599c76',\n            cUPMDTk: \"\\/backend-api\\/conversation?__cf_chl_tk=UNUFZGGTs2H1Z9EMEujiVinY2IKdeQhtTBEx5hGqK6s-1685660844-0-gaNycGzNFGU\",\n            cFPWv: 'g',\n            cTTimeMs: '1000',\n            cMTimeMs: '0',\n            cTplV: 1,\n            cTplB: 'cf',\n            cK: \"\",\n            cRq: {\n                ru: 'aHR0cHM6Ly9jaGF0Lm9wZW5haS5jb20vY2hhdC9iYWNrZW5kLXBhaWQvYXBpL2NvbnZlcnNhdGlvbg==',\n                ra: 'TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTEyLjAuMC4wIFNhZmFyaS81MzcuMzY=',\n                rm: 'UE9TVA==',\n                d: '4A2XaIGRVdjcPzpxgFfZX1+RWDPvJEliFYDEnopipZ5V1cO0rQZ+5bM6kBQib8tWGvAq3KBc/enj9UtLjHyQj9IzizAu7N0ar+S6dUWJq0ENclgZHxaCO120LgGsFOT4puO34sRi8Ds8OmK7FU61ISknZpE4tXUMItWM6hDh9jsoYkJfR/jsSDPVbaz9sAE032m6OIEp4VDDWe5AH9bWyGEyIChqI0s6XtvFBWZirdfM6EmHziBZlO10gxQaA4AtMOZcHonnT4qqBsOPD4SNYJACfWDcm77oqPdwHDJbBqJ7opjRfaJjeTuKSiffXjdQ7G7SjU6MqukQRjnFoC4CEWRc6SssEmw5iOPo5ID+ktD54Qz4cyLsyWgN+Y6bHBhaQNylJEOeeOGTeWQW5iwVf3BB/nycdJgkDDFslhzpRji51eda/2TGwITT1Eau32os4D1YcoGqtHvnUJ5uds8q4pfj5uDUsqxFZR1gP+yPXhVtN9AB3Upt+yFOkvfRy3suTqGfY9TAPI8Thb2W5SVHfbka94U/dgN61OVMQlDp2jr6CQaiPTEyCOq8WRPJ5Wbt2CctxEDwZrSptmHJQE6k4XKHs+82TbDFJkMlvKHcLW5AOslgaIFL5FPs1heWw05Y5oecKkTOZyYIhnlSVJmL9A==',\n                t: 'MTY4NTY2MDg0NC4wNTYwMDA=',\n                m: 'AaLhu+Jsa1OBUvy6Smtv86U1elexBik/wQEmitn0sFI=',\n                i1: 'P+y5wKNedaiVo07cLCRh8A==',\n                i2: 'VDCDtNfwzmDzXxbGBhz1+A==',\n                zh: 'iuyN59AGNgeBFFEOPj72EN+xtBfXXvoCyd1dJnIVFAc=',\n                uh: 'RrzyL1rzMSxlSzoH0Zf/xbDW0NSksqU1W/eDRY5CTuw=',\n                hh: 'foaWmAUHGGlVCZaNUJIHhxzxFNzSPNnVe6rJjiQw728=',\n            }\n        };\n        var trkjs = document.createElement('img');\n        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=7d0b1cd3584a3584');\n        trkjs.setAttribute('alt', '');\n        trkjs.setAttribute('style', 'display: none');\n        document.body.appendChild(trkjs);\n        var cpo = document.createElement('script');\n        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=7d0b1cd3584a3584';\n        window._cf_chl_opt.cOgUHash = location.hash === '' \u0026\u0026 location.href.indexOf('#') !== -1 ? '#' : location.hash;\n        window._cf_chl_opt.cOgUQuery = location.search === '' \u0026\u0026 location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;\n        if (window.history \u0026\u0026 window.history.replaceState) {\n            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;\n            history.replaceState(null, null, \"\\/backend-api\\/conversation?__cf_chl_rt_tk=UNUFZGGTs2H1Z9EMEujiVinY2IKdeQhtTBEx5hGqK6s-1685660844-0-gaNycGzNFGU\" + window._cf_chl_opt.cOgUHash);\n            cpo.onload = function() {\n                history.replaceState(null, null, ogU);\n            };\n        }\n        document.getElementsByTagName('head')[0].appendChild(cpo);\n    }());\n\u003c/script\u003e\n\n\u003c/div\u003e\n    \u003c/div\u003e\n  \u003cscript\u003e!function(){var e=document.createElement(\"iframe\");function t(){var t=e.contentDocument||e.contentWindow.document;if(t){var n=t.createElement(\"script\");n.nonce=\"\",n.innerHTML=\"window['__CF$cv$params']={r:'79271b319741fa72',m:'sCXwl7Hde_jVE6GIOe0wKz4oMt3Lh8w0Eua1mDgehB0-1675216960-0-AYp1IKwNU5u8yMiuEYyoErcqoHVV4YDI+VMoX7mzAvt9fZ4EOB3++PlEm7wtksX3Xttwni3QWV/tKTeRlCy+/nY6nCAYRHzWlB1zXw1KXyx/+B5lo5mvtnyYfuCVVJEWfwzAUnF4MwJWDszLxIwECgs=',s:[0xb58b3307a5,0x39915b3715],u:'/cdn-cgi/challenge-platform/h/g'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);\",t.getElementsByTagName(\"head\")[0].appendChild(n)}}if(e.height=1,e.width=1,e.style.position=\"absolute\",e.style.top=0,e.style.left=0,e.style.border=\"none\",e.style.visibility=\"hidden\",document.body.appendChild(e),\"loading\"!==document.readyState)t();else if(window.addEventListener)document.addEventListener(\"DOMContentLoaded\",t);else{var n=document.onreadystatechange||function(){};document.onreadystatechange=function(e){n(e),\"loading\"!==document.readyState\u0026\u0026(document.onreadystatechange=n,t())}}}();\u003c/script\u003e\u003c/body\u003e\n\u003c/html\u003e\n","message":"Unknown error","param":null,"type":"internal_server_error"}}

**Comment by ztjhz** [comment]
The endpoint (https://free.churchless.tech/v1/chat/completions) is currently down, you can still continue to use the official endpoint.
