### ISSUE TITLE
Generating title without an active gpt-3.5-turbo deployment in Azure creates a generic error message

### ISSUE THREAD

**Issue by Xtrah** [ztjhz/BetterChatGPT#329]
It is not clear that generating title will always use model gpt-3.5-turbo even though the currently active chat uses another model. 

This causes an error message **in the chat** if the (Azure) endpoint doesn't have an gpt-3.5-turbo deployment, even though the chat itself works fine. The error message should maybe somehow either indicate specifically that the error refers to title generation, or title generation should use the selected chat model if using Azure.

![image](https://github.com/ztjhz/BetterChatGPT/assets/12988459/a0a36eb7-f48a-4f33-b21e-1bb0de2ae415)

**Comment by ztjhz** [comment]
Thanks for bringing this up, we will make the error message clearer.
