### ISSUE TITLE
Title generation isn't included in calculated costs

### ISSUE THREAD

**Issue by Xtrah** [ztjhz/BetterChatGPT#330]
Title generation isn't included in calculated costs (or it might be incorrectly calculated).

Tested in #329 when using Azure endpoint with GPT-4, considering that title generation uses gpt-3.5-turbo, it should incur a small charge on the gpt-3.5-turbo estimation when generating a thread title, but it currently doesn't.

**Comment by ztjhz** [comment]
The total token costs are updated here: https://github.com/ztjhz/BetterChatGPT/blob/main/src/hooks/useSubmit.ts#L186

**Comment by Xtrah** [comment]
Considering the title generation uses gpt-3.5-turbo, shouldn't there be a gpt-3.5-turbo charge calculated here then, or does it add onto the estimated gpt-4 cost?

![image](https://i.imgur.com/Iha824k.gif)

**Comment by ztjhz** [comment]
This is a bug, currently it adds the cost to the current model chosen.
