### ISSUE TITLE
[Feature] Add Support for Multiple API Keys to Handle Concurrent Requests

### ISSUE THREAD

**Issue by Jupalaja** [ztjhz/BetterChatGPT#342]
## Summary:
Add support for configuring and using multiple API Keys to handle multiple requests at the same time, eliminating request blocking and enhancing the overall app's performance.

#### Background:
Currently, the app only supports using a single API Key for processing requests. This results in the app freezing when sending a request. By adding support for multiple API Keys, the app could process requests concurrently, allowing users to make multiple requests to the OpenAI API simultaneously and improving app performance.

**Please share any thoughts, ideas, or feedback about this feature request for further development and consideration. The primary focus of this request is to prevent app freezing during requests by allowing users to enter and utilize multiple API keys for parallel processing.**

**Comment by lindebuyer** [comment]
Dont the app already possible handle multiple request? Is just single thread chatting which meant user can only interact one chat at a time. Identical from official app.

**Comment by NN1985** [comment]
This doesn't need to be a feature. You only need one API key to do this. OpenAI allows hundreds of multiple requests per minute concurrently as long as you don't hit the overall rate limit. Betterchatgpt allows you to run multiple requests as long as you are in a separate thread.

See this video example I just did:

https://github.com/ztjhz/BetterChatGPT/assets/129909563/3d1a3cdc-1937-458a-8f20-f8b4e1da0d88

**Comment by Jupalaja** [comment]
I see, to prevent synchronization problems, I use `Google Sync`. However, it doesn't work well when multiple tabs are involved. I'm referring to how the app disables the ability to open new chats in the same tab. 

Here's a video of the app disabling the option to create a new chat, any suggestions for working around this feature?

https://github.com/ztjhz/BetterChatGPT/assets/82126880/5c9ffb2b-de35-4b79-8382-555994af0f60

**Comment by ttimasdf** [comment]
Support of multiple key almost always involves key reselling or usage of stolen keys. Commercial version of OpenAI API is rather stable and never failed on handling requests, especially for this single page application .

If you are looking for repackaging this application for commercial use, I'd recommend you look for other projects, like oneapi

**Comment by ishaan-jaff** [comment]
@ttimasdf @Jupalaja @lindebuyer @NN1985 

I'm the maintainer of LiteLLM we provide an Open source proxy for load balancing Azure + OpenAI + Any LiteLLM supported LLM
**It can process (500+ requests/second)**

From this thread it looks like you're trying to load balance between diff OpenAI keys. Our proxy will allow you to maximize throughput by load balancing between Azure OpenAI instance - I hope our solution makes it easier for you. **(i'd love feedback if you're trying to do this)**

## Here's the quick start:
Doc: https://docs.litellm.ai/docs/simple_proxy#load-balancing---multiple-instances-of-1-model

## Step 1 Create a Config.yaml
```python
model_list:
  - model_name: gpt-4
    litellm_params:
      model: azure/chatgpt-v-2
      api_base: https://openai-gpt-4-test-v-1.openai.azure.com/
      api_version: "2023-05-15"
      api_key: 
  - model_name: gpt-4
    litellm_params:
      model: azure/gpt-4
      api_key: 
      api_base: https://openai-gpt-4-test-v-2.openai.azure.com/
  - model_name: gpt-4
    litellm_params:
      model: azure/gpt-4
      api_key: 
      api_base: https://openai-gpt-4-test-v-2.openai.azure.com/
```

## Step 2: Start the litellm proxy:
```
litellm --config /path/to/config.yaml
```

## Step3 Make Request to LiteLLM proxy:
```
curl --location 'http://0.0.0.0:8000/chat/completions' \
--header 'Content-Type: application/json' \
--data ' {
      "model": "gpt-4",
      "messages": [
        {
          "role": "user",
          "content": "what llm are you"
        }
      ],
    }
'
```
