### ISSUE TITLE
Every phrase is repeated multiple times

### ISSUE THREAD

**Issue by empflow** [ztjhz/BetterChatGPT#346]
My prompt: what is an HTTP directive?

The beginning of the response: An HTTP directiveAn HTTP directive refersAn HTTP directive refers toAn HTTP directive refers to a commandAn HTTP directive refers to a command or instruction includedAn HTTP directive refers to a command or instruction included inAn HTTP directive refers to a command or instruction included in an HTTPAn HTTP directive refers to a command or instruction included in an HTTP (Hypertext TransferAn HTTP directive refers to a command or instruction included in an HTTP (Hypertext Transfer Protocol) message that provides additionalAn HTTP directive refers to a command or instruction included in an HTTP (Hypertext Transfer Protocol) message that provides additional information or directives to the server or the clientAn HTTP directive refers to

The response itself is massive (14571 words)

I tried starting new conversations and asking it different things, but I still get a similar result every time.
I also tried deleting all cached data like cookies but it didn't help either.

Are you aware of this issue?

**Comment by PrettyXD** [comment]
Same, no matter the prompt the answer gets repeated many times.

**Comment by Srcsm** [comment]
Generated same fantasy name lists and got 13k lines this morning. :(

**Comment by empflow** [comment]
seems to be resolved
