### ISSUE TITLE
How can I increase the typing speed of the output - GPT4 ?

### ISSUE THREAD

**Issue by magedhelmy1** [ztjhz/BetterChatGPT#347]
Hi, I was wondering if there is somewhere in the code where can I tweak the typing speed or make it paste the output in chunks like it is in GPT4-32k. Thank you! :)

**Comment by mariodian** [comment]
Yeah, it makes sense. You'd have to heavily modify [useSubmit.ts](https://github.com/ztjhz/BetterChatGPT/tree/6a022d94249e5f7f6ba67de3aeac5d87a5aa7d45/src/hooks/useSubmit.ts) which currently only reads from stream.
