### ISSUE TITLE
BetterGPT is Stealing API Keys DO NOT USE

### ISSUE THREAD

**Issue by fenrirlycan** [ztjhz/BetterChatGPT#353]
I gave bettergpt.chat a unique API key on June 13th at approximately 3pm, and had no other keys at the time, and _did not use the service at all_. In fact, I haven't used the OpenAI API for anything else before and just gave them my card info today. Yet, when I went to my usage on OpenAI's website, I could see that I was using tokens on the 14th, which was **tomorrow** while it was very much only 6pm here. This is obviously because the person using it was in Singapore. I closely analyzed my usage the entire time because I was very suspicious of the service, and lo and behold, my usage spiked up a moment ago, so I revoked the key.

They also obfuscate which key you give to the website, so you have a hard time narrowing down which one it is. I only had one key, and the key they showed on their website was not the key I gave them, yet when I revoked my key, then tried to test the service (for the first time) it said my key was invalid. Luckily I was only swindled for a meager penny.

These people are stealing tokens on a massive scale. Absolutely do not use this service, just pay for the tokens from OpenAI directly and wait for the opportunity to use the extended token models when they roll out more access.

**Comment by fenrirlycan** [comment]
![2023-06-14_01-35](https://github.com/ztjhz/BetterChatGPT/assets/122252200/28a27846-d3fa-484c-a3ba-dfc2c3624b7d)

**Comment by beornf** [comment]
@fenrirlycan Regarding tracking the usage of keys from OpenAI there are two things to note. The OpenAI shows the usage in UTC time not your local time zone. Also I have noticed there is some delay after using your token and usage appearing on the OpenAI website around 1-2 hours.

**Comment by fenrirlycan** [comment]
There is some delay, for sure, however, I did not use the key for anything other than bettergpt.chat. It simply cannot be a mistake. I've not made an API key for anything else and just linked my debit card today, to specifically use their service ...that leaves only one conclusion.

I already seem to be making people mad. If my warning falls on deaf ears, then by all means, carry on. I didn't have any mal-intent. Just trying to give warning to something deductively apparent.

**Comment by beornf** [comment]
Which API endpoint did you use? Since I use the api.openai.com endpoint and had a quick look over the source code I assumed there is no possibility of MITM attack.

**Comment by fenrirlycan** [comment]
I used the same end point. Is it possible that we aren't seeing the actual code being run on the website https://bettergpt.chat? There's no way to verify what we see on this GitHub is actually what that server is doing. I wouldn't have said anything if this wasn't extremely suspect, to say the least. Especially since it seems like I'm going to become public enemy number one for it.

**Comment by fenrirlycan** [comment]
Whatever, I gave my two cents. Be careful people.

**Comment by PriNova** [comment]
@fenrirlycan Do you use browser extensions which could potentially sniff cookies?
I think of some ChatGPT extensions, which can have potentially sniff you API key, because some of them can have full access on all openai.com url's

**Comment by fenrirlycan** [comment]
Like I said, I used the API key for nothing else, I use no other ChatGPT extensions, or extensions which are even aware of my use of ChatGPT. I'm extremely security conscious, I've been in cyber security since I was 16 and I'm in my 30's now. The whole reason I didn't use the service after adding my key and waited was to test for _this exact reason_.

I invite anyone to conduct the same research on a fresh account and a single API key to verify my claims and we can gladly chalk it up to something  else. This wasn't a malicious browser extension, cause I have no ChatGPT extensions or anything with access to my cookies which could have done something like this.

**Comment by mariodian** [comment]
https://bettergpt.chat/ cannot steal your key because the only request it makes is directly to the openai API as you can see in the screenshot below.

<img width="1579" alt="Screenshot 2023-06-14 at 11 46 18 PM" src="https://github.com/ztjhz/BetterChatGPT/assets/3636406/b0516acc-2e59-4aea-b835-f70902467f6e">

**Comment by XOKP** [comment]
It's very plausible that a local malware, such as a browser extension, could be compromising your API key.

**Comment by lindebuyer** [comment]
I've been modify bettergpt and use as private project for months. It's a total front end applications and tho i put my key in the backend, Because mine is a paid service. But i audited all the codes. 

Tho i am not some celebrity GitHub god, but this project’s integrity is intact. And is well managed.

**Comment by fenrirlycan** [comment]
So the mystery gets even stranger.

Upon querying OpenAI for additional insights, a new layer to this conundrum was revealed: 

![2023-06-14_16-12](https://github.com/ztjhz/BetterChatGPT/assets/122252200/8e01d9ae-b19c-4eee-bc91-00b527eb8147)
![2023-06-14_16-12_1](https://github.com/ztjhz/BetterChatGPT/assets/122252200/87919b4d-3e2e-43b4-bd4d-ad1a82fdf9b5)


In all honesty, I'm at a loss. I can say without hesitation, I have no idea what is happening here. It seems my API key had been used to transmit prompt tokens, yet there were no corresponding completions. Curiously enough, it was employing the ada-002 model. 

It's not my intention to drown you in pedestrian explanations or self-justifications. But I must express my regret over my impulsive response and so quickly jumping the gun. Fueled by concern and indignation (and quite frankly, anger), my intention was to alert others if indeed their trust was being betrayed. However, I now realize my actions were half-assed and erroneous. But I ask each of you, using full empathy, if you were presented with the information I had at the time, in the same circumstances, what would you deduce was going on?

To the developer and to the community I sought to join, please accept my heartfelt apologies. My choice of words was harsh, and in place of accusations, I should have invited collective inquiry and shared the information I had. Yesterday was an emotionally-charged day, and my judgement was clouded.

I still cannot definitively explain what happened here, but I will refrain from unfairly accusing the developer based on the present, indecipherable evidence.

Please be cautious about sharing your OpenAI API private keys. It's foolish to even state, if not impossible, to fully understand the what is going on behind the server's curtains unless you have root access. Any security professional worth their salt would agree with this statement. Nothing is safe.

In humility and with respect, I hope to be afforded your understanding. We all make missteps and I hope that this inspired some people to be a little more security conscious. Consider this apology a closing to this topic--I hope further investigation occurs so we can be sure of the inner-workings of a third party service we are trusting with our private keys. 

Jing Hua, I apologize if I caused you any distress, I didn't sleep well last night over this myself. I too believe in, equal, truly OpenAI for all, and would donate to the cause if I could determine what exactly was going on here. Take care everyone.

**Comment by PriNova** [comment]
You are sure not using LangChain text-embedding or some other service, which has some LLM memory as feature?

**Comment by fenrirlycan** [comment]
The only other AI thing is use is GPT4All, and I haven't put a private key into it, because I have a ChatGPT premium account. I use it to test other LLMs (with incredible results!). With the current information as it stands, I conclusively can say what happened can not be determined. 

I'll investigate further and give any updates I can. We should be extra cautious with our keys is the lesson to be learned here. Also for me not to be a dick and jump the gun like that.
