### ISSUE TITLE
del

### ISSUE THREAD

**Issue by Jarrodsz** [ztjhz/BetterChatGPT#365]
Del

**Comment by mariodian** [comment]
No, there would need to be some kind of backend that could write to the filesystem.

**Comment by Michspirit99** [comment]
> No, there would need to be some kind of backend that could write to the filesystem.

Is there not a function to handle outputting to the local file system in JS? Why would that require an entire backend?

**Comment by mariodian** [comment]
> Is there not a function to handle outputting to the local file system in JS? Why would that require an entire backend?

There is, in node.js. 

Browser can’t do that for security reasons. Imagine you open a random website and it starts saving backdoors on your disk.
