### ISSUE TITLE
Why doesn't it accept my api key?

### ISSUE THREAD

**Issue by Pakrohk** [ztjhz/BetterChatGPT#390]
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

Message from Better ChatGPT:
We recommend changing your API endpoint or API key

**Comment by mariodian** [comment]
Seems like you need to raise your hard quota in the openai dashboard. Did you set it to something small like a $1?

**Comment by Pakrohk** [comment]
> Seems like you need to raise your hard quota in the openai dashboard. Did you set it to something small like a $1?

I did not change anything, everything is default

**Comment by ztjhz** [comment]
It could be that your free quota has expired.

**Comment by yRrru** [comment]
the same question...

**Comment by Shlyapochnik6** [comment]
Hello! Have you resolved this issue? I'm facing the same problem. I have the default settings, and my token was just created.
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

Message from Better ChatGPT:
We recommend changing your API endpoint or API key
