### ISSUE TITLE
[Warning] [Trademark protection] Gpt is a protected trademark

### ISSUE THREAD

**Issue by DaSilvaRemi** [ztjhz/BetterChatGPT#414]
I search on internet about "GPT" and it's a tradewark. So normally you can't use it for your website :  https://alter.com/trademarks/gpt-97733259

**Comment by MatthewScholefield** [comment]
That's just a trademark application. It was actually refused by the USPTO ~3 months ago ([see here](https://tsdr.uspto.gov/documentviewer?caseId=sn97733259&docId=NFIN20230525093517&linkId=1#docIndex=0&page=1)):
![image](https://github.com/ztjhz/BetterChatGPT/assets/5875019/36d43567-bfbc-4b6e-b5e9-b5941112abda)

**Comment by DaSilvaRemi** [comment]
Thanks @MatthewScholefield I don't see it
