### ISSUE TITLE
support azure-openai gpt-35-turbo models (1106 and 0125)

### ISSUE THREAD

**Issue by fcakyon** [ztjhz/BetterChatGPT#518]
Hey @ztjhz !

Thanks for the excellent repo!

Azure Openai models are named 'gpt-35-turbo-1106' instead of 'gpt-3.5-turbo-1106'. Could you add a mapping for azure endpoints by checking the endpoint URL? Azure endpoints are in this format: 'https://DEPLOYMENT-NAME.openai.azure.com/'. 

Something like this would work: if 'openai.azure.com' is in endpoint_url, change 'gpt-3.5-turbo-1106' to 'gpt-35-turbo-1106'.

Bests

**Comment by phly95** [comment]
Or perhaps allow users to type their own model names.

**Comment by ztjhz** [comment]
Hi, the azure endpoints are already mapped here: https://github.com/ztjhz/BetterChatGPT/blob/main/src/api/api.ts#L18

**Comment by fcakyon** [comment]
> gpt-35-turbo-1106

@ztjhz thanks for your response!

However, that list is not complete. For instance, it doesn't include the latest gpt3.5 versions: `gpt-3.5-turbo-1106`
