### ISSUE TITLE
Add the new GPT4 model 0125

### ISSUE THREAD

**Issue by DigitallyTailored** [ztjhz/BetterChatGPT#520]
A new `gpt-4-0125-preview` model (and a few more bits) were released yesterday: https://openai.com/blog/new-embedding-models-and-api-updates

![image](https://github.com/ztjhz/BetterChatGPT/assets/13086157/70442838-5981-4c5a-aa47-8ccb76f417d3)

It would be great to have the latest models added as model options.

**Comment by DigitallyTailored** [comment]
Made a PR for this here: https://github.com/ztjhz/BetterChatGPT/pull/521

**Comment by 7flash** [comment]
Also gpt-3.5-turbo-0125 but I think it's automatically aliased to current gpt-3.5-turbo

**Comment by khfung** [comment]
should be just gpt-4-turbo-preview

> For those who want to be automatically upgraded to new GPT-4 Turbo preview versions, we are also introducing a new gpt-4-turbo-preview model name alias, which will always point to our latest GPT-4 Turbo preview model.

**Comment by DigitallyTailored** [comment]
@ztjhz do you know when this will be added? Quite keen to try the new model in better gpt.

**Comment by ztjhz** [comment]
It has just been added.

**Comment by DigitallyTailored** [comment]
Amazing, thank you 🙌
