### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by gkrawiec** [ztjhz/BetterChatGPT#553]
project seems dead. If yes, any forks that support chatgpt v4 turbo?

**Comment by Xtrah** [comment]
What do you mean "chatgpt v4 turbo"?

**Comment by gkrawiec** [comment]
> What do you mean "chatgpt v4 turbo"?

GPT-4 Turbo
https://openai.com/pricing

**Comment by Xtrah** [comment]
It was added more than a month ago? 😕 https://github.com/ztjhz/BetterChatGPT/commit/ecad41fd729cb36968aa4866391692d02a51af89

**Comment by gkrawiec** [comment]
I guess we have to wait for a new release then. thanks.

**Comment by Xtrah** [comment]
It's working for me...

<img width="213" alt="Skjermbilde 2024-03-10 kl  01 21 56" src="https://github.com/ztjhz/BetterChatGPT/assets/12988459/b911fad2-6690-418b-b5cf-8ec015927d35">

**Comment by gkrawiec** [comment]
which version are you running? the latest for MacOS from the releases page seems to be 1.0.4 from june last year.

**Comment by Xtrah** [comment]
Yeah, we should probably delete that.

The [web version that is hosted on GitHub from this repo](https://bettergpt.chat/) is up to date.

**Comment by gkrawiec** [comment]
there are at least 2 other docker based solutions for this.
https://librechat.ai/
https://chatbotui.com/
probably more out there.

but none other that offer a simple local installation on Mac and windows like betterchatgpt

I hope you dont delete it, but instead update the installable builds.

thanks.
