### ISSUE TITLE
[Feature Request] Suggestions to improve the integration of the new prompt library

### ISSUE THREAD

**Issue by SamuelMiller** [ztjhz/BetterChatGPT#70]
Thank you for introducing the new prompt library. I have some suggestions to improve the integration of the prompt library into the main chat. Currently, users have to select, copy, and paste prompts from the prompt library in Settings into their chats. Here are some ideas to make saving and using prompts easier and to integrate access to the prompt library:

Saving prompts:

1. Add a 'save to library' icon between or next to the edit and trash icons in the chat thread to allow users to save a user/system/assistant prompt directly to the prompt library.

Using prompts:

2. Display a 'copy' icon next to each prompt in the prompt library to allow users to easily copy the prompt to paste into their chats.

3. Allow users to use the name of the prompt in the library as a placeholder in the chat by placing the name of the prompt in curly brackets, for example: {prompt: name of prompt} (or whatever signifier you think would be better). In addition, allowing the use of multiple placeholders in the same prompt would allow users to string prompts together in the same prompt. 

Example of placeholder feature:
Using the default prompt in the library called 'English Translator' as an example, entering the prompt ```{prompt: English Translator}``` in the chat prompt would automatically refer to the saved prompt content in the library.

In this case, the ```{prompt: English Translator}``` placeholder prompt refers to what is saved in the library under that name: 'I want you to act as an English translator, spelling corrector, and improver...' Please note that I want you to only reply with the correction and improvements, and nothing else. Do you understand?"

**Comment by ztjhz** [comment]
Currently, users can utilize the prompt by clicking the button at the bottom right of the text area:

![image](https://user-images.githubusercontent.com/59118459/224761039-8d783157-afda-4c27-aa54-cc27c6f29e89.jpg)

I think your suggestion on the copy to the library is great!

**Comment by SamuelMiller** [comment]
I didn't see the slash option besides the save button. Sorry about that. That's actually a better idea!!! than my placeholder one.

**Comment by ztjhz** [comment]
No worries! Perhaps the slash button could be more user friendly and intuitive.

**Comment by SamuelMiller** [comment]
This request has been fulfilled with the slash option to insert prompts.
