### ISSUE TITLE
[Freature Request] Add ability to import and export Prompt Library (.csv format)

### ISSUE THREAD

**Issue by SamuelMiller** [ztjhz/BetterChatGPT#71]
I would like to suggest adding the ability to import and export the Prompt Library, starting with the CSV format. This would allow users to import, save, and share lists such as the one available at https://github.com/f/awesome-chatgpt-prompts/blob/main/prompts.csv. 

By adding the CSV feature, users would be able to create a spreadsheet of their favorite prompts, save as CSV, and then import them into FreeChatgpt. This feature would also make it easier for users to edit their Prompt Library by allowing them to import the CSV file into a spreadsheet editor. 

An advanced feature could be added to allow users to select all or specific prompts they want to import or export.  Perhaps this could be implemented through a separate dialogue box, where the user can check what they want to export or import.

PS: If it hasn't been done yet, the Prompts Library should be added to the JSON export/backup. Thanks!

**Comment by ztjhz** [comment]
What do you mean by "Awesome prompt.csv is full of non-CSV related code"?

**Comment by SamuelMiller** [comment]
My mistake. Somehow the way/where I downloaded it added a bunch of HTML code.  Looking at the raw version (https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv), it looks like good ol' CSV to me.
