### ISSUE TITLE
[idea] Create more vertical space in the sidebar menu for chat history

### ISSUE THREAD

**Issue by SamuelMiller** [ztjhz/BetterChatGPT#79]
I suggest creating more vertical space for Chat History in the sidebar of FreeChatGPT. Notice that the official app (lower left image) has more vertical space for chat history compared to the Freechatgpt sidebar (right image). 

Here are a couple of ideas for creating more vertical space for chat history which could be singularly done or combined:

1. Consolidate some of the menu items in the lower part of the sidebar by combining related items into the same category. For example, "Made By Jing Jua", which is an "About" topic, could be included in the "About & Sponsor" section. If you wanted to keep the "Made By Jing Jua" still prominent, as its own menu item, another possibility would be to move  "Import/Export" to the "Settings" section. There are several other possible configurations to consider. By consolidating at least two menu items, more vertical space could be created for Chat History.

2. A more drastic approach would be to make the lower menu below the chat history a collapsible slide-up/slide-down menu. This would essentially allow most of the vertical sidebar to be dedicated to the Chat History, and users could access the lower menu items by clicking a button to expand the menu when necessary. This way, more chat history would be more prominent and easily accessible. When first loading Freechatgpt, the menu could be expanded by default, and users could collapse or minimize it as they prefer.

PS: As a side note, I notice that I am not currently able to access the lower sidebar menu using "tab" on Mac (without a mouse). Whatever you do decide to do with the sidebar layout, I recommend testing the web app to make sure it is fully accessible with a mouse, just using a keyboard.

| ChatGPT web app | FreeChatGPT web app |
| --------------- | ------------------- |
| ![chatgptsidebar](https://user-images.githubusercontent.com/10334059/225075764-471853e7-bd16-4b67-a546-561a9bcebac0.png) | ![freechatgpt](https://user-images.githubusercontent.com/10334059/225075756-46c1e48c-ac3d-4fc2-bc04-90294e6d4c7c.png) 

Thanks for all your hard work!!

**Comment by flycran** [comment]
我觉得可以做一个折叠功能

**Comment by coranholmes** [comment]
我觉得可以创建层级目录进行会话管理~

**Comment by SamuelMiller** [comment]
Suggestion number two, the collapsable settings menu, has been implemented. You can close the request if you wish.

**Comment by SamuelMiller** [comment]
Suggestion number two, the collapsable settings menu, has been implemented.
