### ISSUE TITLE
[Bug Report]Content generated in wrong chat box when toggling tabs

### ISSUE THREAD

**Issue by mikeboly** [ztjhz/BetterChatGPT#95]
Open chat box A and start generating content.
Toggle to chat box B while content is still being generated in chat box A.
Observe that content continues to be generated in chat box B instead of A.
Expected behavior:
Content should continue to be generated in the original chat box (A) even if tabs are toggled.

Actual behavior:
Content is generated in the newly opened chat box (B) instead of the original chat box (A).

**Comment by Lyapsus** [comment]
Also you can trigger a similar behavior if you add another user message while it generates the answer for the previous one, the answer will continue generating in a new user message box
