### ISSUE TITLE
feature: System Prompts

### ISSUE THREAD

**Issue by saliksik** [ztjhz/BetterChatGPT#96]
Hi!

The prompts library is very much helpful and I hope you can also replicate it for system prompts. So, we can have own our system prompts library.

Thank you.

**Comment by SamuelMiller** [comment]
Perhaps, I am misunderstanding you, but doesn't FreeChatGPt already have that feature with the existing prompt library, which you can use for system or user roles? just select the "system" role option in the chat and then click on the forward slash "/" icon in the lower right and select the prompt.

**Comment by haroldwinstob** [comment]
@SamuelMiller selecting the system role and clicking here and there is the hussle he is trying to avoid. adding a user-defined chat configuration is the solution.

**Comment by Lyapsus** [comment]
Would be good to be able to rewrite the default system prompt to not change it in every new chat
